title: Beep Beep!
subtitle:  This kid loves building ROBOTS!
description: >- # this means to ignore newlines until "baseurl:"
  Now where does this go?

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog

# Edit these details  

author_logo: profile.png
author: Vihaan Akshaay
author_bio: <p>I recently completed my M.S. in Computer Science at the <a href="https://www.ucsb.edu/">University of California, Santa Barbara</a>, where I was primarily mentored by <a href="https://www.cs.cmu.edu/~leili/">Prof. Lei Li</a>. My research focused on machine learning applications, particularly in reinforcement learning and computer vision. I worked on a project in <a href="https://neurips.cc/virtual/2023/78637">Goal-Conditioned Reinforcement Learning</a>, jointly guided by <a href="https://sites.cs.ucsb.edu/~yuxiangw/">Prof. Yu-Xiang Wang</a>, developing a novel framework for bi-directional goal conditioning in state space search problems. Additionally, I contributed to the <a href="https://esurf-carbon.geol.ucsb.edu/people/gen-li">AI for Earth</a> initiative, collaborating with <a href="https://esurf-carbon.geol.ucsb.edu/people/gen-li">Prof. Gen Li</a> to create a dataset for landslide detection, leveraging 40 years of Landsat imagery and integrating Digital Elevation Model data to enhance detection accuracy.</p> <p>I earned my B.Tech in Mechanical Engineering and M.Tech in Robotics from <a href="https://www.iitm.ac.in/">IIT Madras</a>, where my Master's thesis, focused on unsupervised behavior recognition in mice, was guided by <a href="http://www.cse.iitm.ac.in/~ravi/">Prof. B. Ravindran</a> and <a href="https://www.jax.org/research-and-faculty/faculty/vivek-kumar">Dr. Vivek Kumar</a> from The Jackson Laboratory. At IIT Madras, I led the <a href="https://ed.iitm.ac.in/~asokan/">iBot Robotics Club</a> and developed the award-winning <a href="https://home.iitm.ac.in/boby/">ARTEMIS railroad crack detection robot</a> under <a href="https://ed.iitm.ac.in/~asokan/">Prof. Asokan Thondiyath</a>. During this time, I also worked on analyzing stability factors of Deep Q-Networks with <a href="https://sites.google.com/site/sivatheja/">Prof. Siva Theja Maguluri</a> at <a href="https://www.gatech.edu/">Georgia Tech</a> and kernelizing eDRVFLs, a class of deep randomized neural models, with <a href="https://www3.ntu.edu.sg/home/epnsugan/">Prof. P. N. Suganthan</a> at <a href="https://www.ntu.edu.sg/">NTU Singapore</a>.</p>
author_email: "vihaanakshaay@gmail.com"
author_location: Santa Barbara, California
typewrite-text: For some reason I've decided to log my prattle and rants here! I've warned you! xD 

author_work_experiences:
            - company_name: Jackson Laboratory
              company_logo: JAX.png
              company_url: https://www.kumarlab.org
              designation: Graduate Student Researcher
              description: Developed unsupervised techniques to discover stereotyped behaviours exhibited by mice moving in a fixed arena. Computer Vision models were used for pose estimation from video data recorded by Jackson Labs are improved. By modeling behaviours as hierarchies, new option discovery algorithms were implemented to identify repeated behaviours. Dr. Ravindran B, Indian Institute of Technology Madras & Dr. Vivek Kumar, Jackson Labs, Bar Harbor, Maine.
              visibility: true
            - company_name: iBot Club, Centre for Innovation
              company_logo: ib.png
              company_url: http://cfi.iitm.ac.in/wordpress/index.php/ibot-club/
              designation: iBot(Robotics) Club Head
              description: Managed and mentored various projects as well as conducted robotics oriented session with the aim of improving the tech culture in the institute.
              visibility: true
            - company_name: Ramakrishna Math, Chennai
              company_logo: rkm.png
              company_url: https://chennaimath.org/
              designation: Robotics Intern
              description: Worked on 'Biley Bot', a lifelike, interactive humanoid robot of young Swami Vivekananda, soon to be displayed in Vivekanandar House Museum, Chennai. 
              visibility: true
            - company_name: Toyota Kirloskar Motor Pvt Ltd
              company_logo: toyota.png
              company_url: https://en.wikipedia.org/wiki/Toyota_Kirloskar_Motor
              designation: Summer Engineering Intern
              description: Industrial internship with on-field experience from a reputed manufacturing factory. Experience on workshop floor included a project study on Backdoor Cushion Rubber Miss Elimination.
              visibility: true

author_education_details:
              - college_logo: ucsb.jpeg
                college_name: University of California, Santa Barbara
                college_url: https://www.ucsb.edu
                college_degree: Master of Science 
                description: Master of Science in Computer Science (Machine Learning Specialization)
                visibility: true
              - college_logo: iitmlogo.png
                college_name: Indian Institute of Technology, Madras
                college_url: https://www.iitm.ac.in/
                college_degree: Dual Degree (B.Tech in Mechanical Engineering + M.Tech in Robotics) 
                description: Bachelor of Technology in Mechanical Engineering & Inter Disciplinary Master of Technology in Robotics
                visibility: true
              - college_logo: udacity.png
                college_name: Udacity
                college_url: https://www.udacity.com/course/robotics-software-engineer--nd209
                college_degree: Robotics Software Engineer Nanodegree 
                description: Programmed various robots in simulation and worked with Jetson TX2 hardware implementing various robotic algorithms(Localization, Mapping, SLAM, Path Planning and Navigation, 3D perception, Deep Learning, Manipulator Kinematics) and tools(ROS using python & C++, RViz, Gazebo and more).
                visibility: true

author_teaching_details:
              - college_logo: ucsb.jpeg
                college_name: University of California, Santa Barbara
                course_name: CMPSC 130A - Data Structures & Algorithms
                advisor_name: Prof. Eric Vigoda
                course_url: https://sites.cs.ucsb.edu/~vigoda/130A-Fall23/
                visibility: true
              - college_logo: ucsb.jpeg
                college_name: University of California, Santa Barbara
                course_name: CMPSC 165A - Artificial Intelligence [Spring 2023]
                advisor_name: Prof. Yu-Xiang Wang
                course_url: https://sites.cs.ucsb.edu/~yuxiangw/classes/AICourse-2023Spring/
                visibility: true
              - college_logo: iitmlogo.png
                college_name: Indian Institute of Technology, Madras
                course_name: CS6700 - Reinforcement Learning [Spring 2022]
                advisor_name: Prof. Balaraman Ravindran
                course_url: http://www.cse.iitm.ac.in/~ravi/
                visibility: true

author_project_details:
              - project_thumbnail: SRE.png
                project_title: Bi-Directional Goal-Conditioning for State Space Search Problems
                project_description: Developed the ‘SRE-DQN’ (Scrambler-Resolver-Explorer) framework, leveraging bi-directional task generation through ‘Foresight Relabelling’ and goal-conditioned DQN.
                project_url: https://neurips.cc/virtual/2023/78637
                visibility: true
              - project_thumbnail: HRL_Mouse.png
                project_title: Cascaded Deep Monocular 3D Pose Estimation with Evolutionary Synthetic Training Data
                project_description:  With the first step of identifying key points from ample raw video data for unsupervised behavior recognition using option discovery, this project proposes using open-source three-dimensional synthetic animated mouse models to improve existing pose and estimation models.
                project_url: https://vihaanakshaay.github.io/assets/reports/Cascaded_Deep_Monocular_3D_Pose_Estimation_with_Evolutionary_Synthetic_Training_Data.pdf
                visibility: true
              - project_thumbnail: EarthAI.png
                project_title: AI for Earth - Landslide Detection
                project_description:  Developing a deep learning model for landslide prediction using Multi-band Satellite Imagery, benchmarking against Mask RCNN and YOLO models for effective instance segmentation across diverse regions.
                project_url: https://github.com/VihaanAkshaay/AIEarth
                visibility: true
              - project_thumbnail: EUNet.png
                project_title: Edge-Attention U-Net for Shoreline Detection
                project_description:  Developed a U-Net with Edge-based Attention mechanism for Binary Semantic Segmentation, enhancing shoreline detection accuracy on the Satellite-2 Water Edge Dataset compared to standard U-Net and Attention U-Net models.
                project_url: https://vihaanakshaay.github.io/assets/reports/EdgeAttentionUNet.pdf
              - project_thumbnail: graph_ml.png
                project_title: Interactive Traffic Classification using Semi-Supervised Graphical Approaches
                project_description:  By leveraging graphical machine learning models (such as GCN and DGCNN), using psuedo-labeling and exploiting the dependencies between bursts, we achieved near State-of-the-Art performance in interactive network traffic classification with smaller models (0.2% the size of a BERT-based model).
                project_url: https://vihaanakshaay.github.io/assets/reports/Graph_ML_Report.pdf
                visibility: true
              - project_thumbnail: ARTEMIS.png
                project_title: ARTEMIS - Railroad Crack Detection Robot
                project_description: ARTEMIS is an autonomous robot that traverses inbetween the railway tracks, detects faults and sends the coordinates for further action to be taken.
                project_url: https://www.jamesdysonaward.org/2017/project/railroad-crack-detection-bot/
                visibility: true
              - project_thumbnail: picknplace.png
                project_title: Robotic Arm - Pick and Place
                project_description: The goal of the project is to solve is to simulate a robotic arm and perform a pick-and-place exercise very similar to Amazon Robotics Challenge.
                project_url: https://github.com/VihaanAkshaay/Project_Robo-ND_Robotic-Arm_Pick-And-Place
                visibility: true
              - project_thumbnail: RoboND3DPerception.png
                project_title: 3D Perception Project
                project_description: The goal of this project is to program a PR2 to identify and acquire target objects from a cluttered space and place them in a bin. The project is based on the 'Stow Task' portion of Amazon's Robotics Challenge.
                project_url: https://github.com/VihaanAkshaay/Project_Robo-ND_3D-Perception-Project
                visibility: true
              - project_thumbnail: RoboNDproj4.png
                project_title: Robotic Arm - Pick and Place
                project_description: In a simulated environment, given camera input from a drone, the goal is to train a fully convoluted neural network to identify the location of a moving target and to control the drone to follow the same.
                project_url: https://github.com/VihaanAkshaay/Project_RoboND_Follow-Me
                visibility: true                

# social links
github_username:  VihaanAkshaay
linkedin_username: vihaanakshaayrajendiran
instagram_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )


# wakatime username (coding activity)
wakatime_username: VihaanAkshaay

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true


# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
